# Generated by Django 5.0.4 on 2024-04-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizify_Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
