# Generated by Django 5.0.4 on 2024-04-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizify_Home', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
